
package org.example.bankchannelservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "bankChannelService", targetNamespace = "http://172.25.140.21:8070/bankChannelService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankChannelService {


    /**
     * 
     * @param amount
     * @param retn
     * @param userNum
     * @param desc
     * @param requestId
     * @param chnlPasWd
     * @param bossId
     * @param requestDate
     * @param chnlNum
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/bankRecharge")
    @RequestWrapper(localName = "bankRecharge", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.BankRecharge")
    @ResponseWrapper(localName = "bankRechargeResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.BankRechargeResponse")
    public void bankRecharge(
            @WebParam(name = "chnlNum", targetNamespace = "")
                    String chnlNum,
            @WebParam(name = "chnlPasWd", targetNamespace = "")
                    String chnlPasWd,
            @WebParam(name = "userNum", targetNamespace = "")
                    String userNum,
            @WebParam(name = "amount", targetNamespace = "")
                    int amount,
            @WebParam(name = "requestDate", targetNamespace = "")
                    XMLGregorianCalendar requestDate,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.INOUT)
                    Holder<String> requestId,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId);

    /**
     * 
     * @param parameters
     * @return
     *     returns _21._140._25._172._8070.bankchannelservice.GetBundlesResponse
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/getBundles")
    @WebResult(name = "getBundlesResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetBundlesResponse getBundles(
            @WebParam(name = "getBundles", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", partName = "parameters")
                    GetBundles parameters);

    /**
     * 
     * @param deductamount
     * @param retn
     * @param desc
     * @param chnlPasWd
     * @param requestId
     * @param bossId
     * @param servicefee
     * @param password
     * @param chnlNum
     * @param discount
     * @param recharetax
     * @param bdpnotax
     * @param userNum
     * @param username
     * @param bundleId
     * @param bdtax
     * @param ait
     * @param servicetax
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/subBundle")
    @RequestWrapper(localName = "subBundle", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.SubBundle")
    @ResponseWrapper(localName = "subBundleResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.SubBundleResponse")
    public void subBundle(
            @WebParam(name = "chnlNum", targetNamespace = "")
                    String chnlNum,
            @WebParam(name = "chnlPasWd", targetNamespace = "")
                    String chnlPasWd,
            @WebParam(name = "userNum", targetNamespace = "")
                    String userNum,
            @WebParam(name = "bundleId", targetNamespace = "")
                    String bundleId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.INOUT)
                    Holder<String> requestId,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "BDPNOTAX", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> bdpnotax,
            @WebParam(name = "BDTAX", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> bdtax,
            @WebParam(name = "RECHARETAX", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> recharetax,
            @WebParam(name = "DISCOUNT", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> discount,
            @WebParam(name = "DEDUCTAMOUNT", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> deductamount,
            @WebParam(name = "SERVICEFEE", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> servicefee,
            @WebParam(name = "SERVICETAX", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> servicetax,
            @WebParam(name = "AIT", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> ait,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId);

    /**
     * 
     * @param amount
     * @param retn
     * @param payMode
     * @param desc
     * @param depositorId
     * @param requestId
     * @param slipNo
     * @param bossId
     * @param depositorDate
     * @param userName
     * @param bankName
     * @param chequeFlag
     * @param passWord
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/bankAddCredit")
    @RequestWrapper(localName = "bankAddCredit", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.BankAddCredit")
    @ResponseWrapper(localName = "bankAddCreditResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.BankAddCreditResponse")
    public void bankAddCredit(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "passWord", targetNamespace = "")
                    String passWord,
            @WebParam(name = "payMode", targetNamespace = "")
                    String payMode,
            @WebParam(name = "bankName", targetNamespace = "")
                    String bankName,
            @WebParam(name = "depositorId", targetNamespace = "")
                    String depositorId,
            @WebParam(name = "amount", targetNamespace = "")
                    int amount,
            @WebParam(name = "slipNo", targetNamespace = "")
                    String slipNo,
            @WebParam(name = "depositorDate", targetNamespace = "")
                    String depositorDate,
            @WebParam(name = "chequeFlag", targetNamespace = "")
                    int chequeFlag,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param balance
     * @param billType
     * @param username
     * @param desc
     * @param dn
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/getUserInfo")
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.GetUserInfoResponse")
    public void getUserInfo(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "billType", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> billType,
            @WebParam(name = "balance", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> balance,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param retn
     * @param balance
     * @param passwd
     * @param desc
     * @param dn
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/getEtopBalance")
    @RequestWrapper(localName = "getEtopBalance", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.GetEtopBalance")
    @ResponseWrapper(localName = "getEtopBalanceResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.GetEtopBalanceResponse")
    public void getEtopBalance(
            @WebParam(name = "PASSWD", targetNamespace = "")
                    String passwd,
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "balance", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> balance,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param subType
     * @param dn
     * @param password
     */
    @WebMethod(operationName = "CHECKSUBSCRIBER", action = "http://172.25.140.21:8070/bankChannelService/CHECKSUBSCRIBER")
    @RequestWrapper(localName = "CHECKSUBSCRIBER", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.CHECKSUBSCRIBER")
    @ResponseWrapper(localName = "CHECKSUBSCRIBERResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.CHECKSUBSCRIBERResponse")
    public void checksubscriber(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "subType", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> subType,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param subType
     * @param dn
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/queryCustNamePlan")
    @RequestWrapper(localName = "queryCustNamePlan", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QueryCustNamePlan")
    @ResponseWrapper(localName = "queryCustNamePlanResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QueryCustNamePlanResponse")
    public void queryCustNamePlan(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "subType", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> subType,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param requestId
     * @param bossId
     * @param dn
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/queryPrepaidBalance")
    @RequestWrapper(localName = "queryPrepaidBalance", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QueryPrepaidBalance")
    @ResponseWrapper(localName = "queryPrepaidBalanceResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QueryPrepaidBalanceResponse")
    public void queryPrepaidBalance(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param requestId
     * @param bossId
     * @param dn
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/queryPostpaidBalance")
    @RequestWrapper(localName = "queryPostpaidBalance", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QueryPostpaidBalance")
    @ResponseWrapper(localName = "queryPostpaidBalanceResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QueryPostpaidBalanceResponse")
    public void queryPostpaidBalance(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param requestId
     * @param bossId
     * @param dn
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/qryUserService")
    @RequestWrapper(localName = "qryUserService", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QryUserService")
    @ResponseWrapper(localName = "qryUserServiceResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QryUserServiceResponse")
    public void qryUserService(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param requestId
     * @param bossId
     * @param dn
     * @param type
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/freeQueryCommand")
    @RequestWrapper(localName = "freeQueryCommand", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.FreeQueryCommand")
    @ResponseWrapper(localName = "freeQueryCommandResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.FreeQueryCommandResponse")
    public void freeQueryCommand(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "TYPE", targetNamespace = "")
                    String type,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param username
     * @param querydate
     * @param desc
     * @param dn
     * @param type
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/queryCdr")
    @RequestWrapper(localName = "queryCdr", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QueryCdr")
    @ResponseWrapper(localName = "queryCdrResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QueryCdrResponse")
    public void queryCdr(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "QUERYDATE", targetNamespace = "")
                    String querydate,
            @WebParam(name = "TYPE", targetNamespace = "")
                    String type,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param planid
     * @param retn
     * @param username
     * @param desc
     * @param requestId
     * @param bossId
     * @param dn
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/modPlan")
    @RequestWrapper(localName = "modPlan", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.ModPlan")
    @ResponseWrapper(localName = "modPlanResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.ModPlanResponse")
    public void modPlan(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "PLANID", targetNamespace = "")
                    String planid,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param requestId
     * @param promid
     * @param bossId
     * @param dn
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/unsubPromo")
    @RequestWrapper(localName = "unsubPromo", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.UnsubPromo")
    @ResponseWrapper(localName = "unsubPromoResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.UnsubPromoResponse")
    public void unsubPromo(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "PROMID", targetNamespace = "")
                    String promid,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param requestId
     * @param promid
     * @param bossId
     * @param dn
     * @param password
     */
    @WebMethod(operationName = "UNSUBPROM4GToSMS", action = "http://172.25.140.21:8070/bankChannelService/UNSUBPROM4GToSMS")
    @RequestWrapper(localName = "UNSUBPROM4GToSMS", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.UNSUBPROM4GToSMS")
    @ResponseWrapper(localName = "UNSUBPROM4GToSMSResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.UNSUBPROM4GToSMSResponse")
    public void unsubprom4GToSMS(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "PROMID", targetNamespace = "")
                    String promid,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param desc
     * @param requestId
     * @param msisdn
     * @param bossId
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/subWirelessCaller")
    @RequestWrapper(localName = "subWirelessCaller", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.SubWirelessCaller")
    @ResponseWrapper(localName = "subWirelessCallerResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.SubWirelessCallerResponse")
    public void subWirelessCaller(
            @WebParam(name = "MSISDN", targetNamespace = "")
                    String msisdn,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param desc
     * @param requestId
     * @param pin
     * @param bossId
     * @param dn
     */
    @WebMethod(operationName = "VCRechargeToOSP", action = "http://172.25.140.21:8070/bankChannelService/VCRechargeToOSP")
    @RequestWrapper(localName = "VCRechargeToOSP", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.VCRechargeToOSP")
    @ResponseWrapper(localName = "VCRechargeToOSPResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.VCRechargeToOSPResponse")
    public void vcRechargeToOSP(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "PIN", targetNamespace = "")
                    String pin,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param requestId
     * @param bossId
     * @param dn
     * @param type
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/subMca")
    @RequestWrapper(localName = "subMca", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.SubMca")
    @ResponseWrapper(localName = "subMcaResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.SubMcaResponse")
    public void subMca(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "TYPE", targetNamespace = "")
                    String type,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param requestId
     * @param promid
     * @param bossId
     * @param dn
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/subProm")
    @RequestWrapper(localName = "subProm", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.SubProm")
    @ResponseWrapper(localName = "subPromResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.SubPromResponse")
    public void subProm(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "PROMID", targetNamespace = "")
                    String promid,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param trandate
     * @param retn
     * @param amt
     * @param desc
     * @param requestId
     * @param bossId
     * @param orderid
     * @param dn
     * @param chnlname
     * @param transid
     */
    @WebMethod(operationName = "RECHARGEBALNEONLINE", action = "http://172.25.140.21:8070/bankChannelService/RECHARGEBALNEONLINE")
    @RequestWrapper(localName = "RECHARGEBALNEONLINE", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.RECHARGEBALNEONLINE")
    @ResponseWrapper(localName = "RECHARGEBALNEONLINEResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.RECHARGEBALNEONLINEResponse")
    public void rechargebalneonline(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "AMT", targetNamespace = "")
                    String amt,
            @WebParam(name = "TRANSID", targetNamespace = "")
                    String transid,
            @WebParam(name = "TRANDATE", targetNamespace = "")
                    String trandate,
            @WebParam(name = "CHNLNAME", targetNamespace = "")
                    String chnlname,
            @WebParam(name = "ORDERID", targetNamespace = "")
                    String orderid,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param desc
     * @param requestId
     * @param msisdn
     * @param bossId
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/unsubWirelessCaller")
    @RequestWrapper(localName = "unsubWirelessCaller", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.UnsubWirelessCaller")
    @ResponseWrapper(localName = "unsubWirelessCallerResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.UnsubWirelessCallerResponse")
    public void unsubWirelessCaller(
            @WebParam(name = "MSISDN", targetNamespace = "")
                    String msisdn,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param dn
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/customerProfileQury")
    @RequestWrapper(localName = "customerProfileQury", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.CustomerProfileQury")
    @ResponseWrapper(localName = "customerProfileQuryResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.CustomerProfileQuryResponse")
    public void customerProfileQury(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param retn
     * @param desc
     * @param requestId
     * @param bossId
     * @param dn
     */
    @WebMethod(operationName = "CHECKMEMBER", action = "http://172.25.140.21:8070/bankChannelService/CHECKMEMBER")
    @RequestWrapper(localName = "CHECKMEMBER", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.CHECKMEMBER")
    @ResponseWrapper(localName = "CHECKMEMBERResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.CHECKMEMBERResponse")
    public void checkmember(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param desc
     * @param requestId
     * @param bossId
     * @param dn
     */
    @WebMethod(operationName = "QRYOWEFEE", action = "http://172.25.140.21:8070/bankChannelService/QRYOWEFEE")
    @RequestWrapper(localName = "QRYOWEFEE", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QRYOWEFEE")
    @ResponseWrapper(localName = "QRYOWEFEEResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QRYOWEFEEResponse")
    public void qryowefee(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc,
            @WebParam(name = "bossId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> bossId,
            @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> requestId);

    /**
     * 
     * @param retn
     * @param amt
     * @param desc
     * @param subtype
     * @param paymentid
     * @param service
     * @param userName
     * @param dn
     * @param passWord
     * @param serviceid
     */
    @WebMethod(operationName = "DEDUCTBALANCENEWSOAP", action = "http://172.25.140.21:8070/bankChannelService/DEDUCTBALANCENEWSOAP")
    @RequestWrapper(localName = "DEDUCTBALANCENEWSOAP", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.DEDUCTBALANCENEWSOAP")
    @ResponseWrapper(localName = "DEDUCTBALANCENEWSOAPResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.DEDUCTBALANCENEWSOAPResponse")
    public void deductbalancenewsoap(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "passWord", targetNamespace = "")
                    String passWord,
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "AMT", targetNamespace = "")
                    String amt,
            @WebParam(name = "SERVICE", targetNamespace = "")
                    String service,
            @WebParam(name = "SERVICEID", targetNamespace = "")
                    String serviceid,
            @WebParam(name = "SUBTYPE", targetNamespace = "")
                    String subtype,
            @WebParam(name = "PAYMENTID", targetNamespace = "")
                    String paymentid,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param retn
     * @param desc
     * @param subtype
     * @param userName
     * @param dn
     * @param passWord
     */
    @WebMethod(operationName = "BALANCEQUERYSOAP", action = "http://172.25.140.21:8070/bankChannelService/BALANCEQUERYSOAP")
    @RequestWrapper(localName = "BALANCEQUERYSOAP", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.BALANCEQUERYSOAP")
    @ResponseWrapper(localName = "BALANCEQUERYSOAPResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.BALANCEQUERYSOAPResponse")
    public void balancequerysoap(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "passWord", targetNamespace = "")
                    String passWord,
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "SUBTYPE", targetNamespace = "")
                    String subtype,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param retn
     * @param desc
     * @param requerid
     * @param dn
     */
    @WebMethod(operationName = "QUERYRECHARGEBANK", action = "http://172.25.140.21:8070/bankChannelService/QUERYRECHARGEBANK")
    @RequestWrapper(localName = "QUERYRECHARGEBANK", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QUERYRECHARGEBANK")
    @ResponseWrapper(localName = "QUERYRECHARGEBANKResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QUERYRECHARGEBANKResponse")
    public void queryrechargebank(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "REQUERID", targetNamespace = "")
                    String requerid,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param retn
     * @param desc
     * @param requerid
     * @param dn
     */
    @WebMethod(operationName = "QUERYSUBBUNDLEBANK", action = "http://172.25.140.21:8070/bankChannelService/QUERYSUBBUNDLEBANK")
    @RequestWrapper(localName = "QUERYSUBBUNDLEBANK", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QUERYSUBBUNDLEBANK")
    @ResponseWrapper(localName = "QUERYSUBBUNDLEBANKResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QUERYSUBBUNDLEBANKResponse")
    public void querysubbundlebank(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "REQUERID", targetNamespace = "")
                    String requerid,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param retn
     * @param desc
     * @param dn
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/queryCustPlan")
    @RequestWrapper(localName = "queryCustPlan", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QueryCustPlan")
    @ResponseWrapper(localName = "queryCustPlanResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QueryCustPlanResponse")
    public void queryCustPlan(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param renttype
     * @param retn
     * @param username
     * @param pwd
     * @param desc
     * @param msisdn
     * @param utype
     * @param password
     */
    @WebMethod(action = "http://172.25.140.21:8070/bankChannelService/authCrbtUser")
    @RequestWrapper(localName = "authCrbtUser", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.AuthCrbtUser")
    @ResponseWrapper(localName = "authCrbtUserResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.AuthCrbtUserResponse")
    public void authCrbtUser(
            @WebParam(name = "MSISDN", targetNamespace = "")
                    String msisdn,
            @WebParam(name = "UTYPE", targetNamespace = "")
                    String utype,
            @WebParam(name = "PWD", targetNamespace = "")
                    String pwd,
            @WebParam(name = "RENTTYPE", targetNamespace = "")
                    String renttype,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param retn
     * @param username
     * @param desc
     * @param dn
     * @param password
     */
    @WebMethod(operationName = "QRYBUNDLE", action = "http://172.25.140.21:8070/bankChannelService/QRYBUNDLE")
    @RequestWrapper(localName = "QRYBUNDLE", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QRYBUNDLE")
    @ResponseWrapper(localName = "QRYBUNDLEResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.QRYBUNDLEResponse")
    public void qrybundle(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

    /**
     * 
     * @param retn
     * @param amt
     * @param username
     * @param desc
     * @param flag
     * @param promid
     * @param dn
     * @param password
     * @param validday
     */
    @WebMethod(operationName = "DONATEFREE", action = "http://172.25.140.21:8070/bankChannelService/DONATEFREE")
    @RequestWrapper(localName = "DONATEFREE", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.DONATEFREE")
    @ResponseWrapper(localName = "DONATEFREEResponse", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", className = "_21._140._25._172._8070.bankchannelservice.DONATEFREEResponse")
    public void donatefree(
            @WebParam(name = "DN", targetNamespace = "")
                    String dn,
            @WebParam(name = "PROMID", targetNamespace = "")
                    String promid,
            @WebParam(name = "AMT", targetNamespace = "")
                    String amt,
            @WebParam(name = "VALIDDAY", targetNamespace = "")
                    String validday,
            @WebParam(name = "FLAG", targetNamespace = "")
                    String flag,
            @WebParam(name = "Username", targetNamespace = "")
                    String username,
            @WebParam(name = "Password", targetNamespace = "")
                    String password,
            @WebParam(name = "RETN", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> retn,
            @WebParam(name = "DESC", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> desc);

}
