
package org.example.bankchannelservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bankChannelService", targetNamespace = "http://172.25.140.21:8070/bankChannelService/", wsdlLocation = "file:/C:/Users/Administrator/Desktop/bankChannelService.wsdl")
public class BankChannelService_Service
    extends Service
{

    private final static URL BANKCHANNELSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKCHANNELSERVICE_EXCEPTION;
    private final static QName BANKCHANNELSERVICE_QNAME = new QName("http://172.25.140.21:8070/bankChannelService/", "bankChannelService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Administrator/Desktop/bankChannelService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKCHANNELSERVICE_WSDL_LOCATION = url;
        BANKCHANNELSERVICE_EXCEPTION = e;
    }

    public BankChannelService_Service() {
        super(__getWsdlLocation(), BANKCHANNELSERVICE_QNAME);
    }

    public BankChannelService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKCHANNELSERVICE_QNAME, features);
    }

    public BankChannelService_Service(URL wsdlLocation) {
        super(wsdlLocation, BANKCHANNELSERVICE_QNAME);
    }

    public BankChannelService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKCHANNELSERVICE_QNAME, features);
    }

    public BankChannelService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankChannelService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankChannelService
     */
    @WebEndpoint(name = "bankChannelServiceSOAP")
    public BankChannelService getBankChannelServiceSOAP() {
        return super.getPort(new QName("http://172.25.140.21:8070/bankChannelService/", "bankChannelServiceSOAP"), BankChannelService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankChannelService
     */
    @WebEndpoint(name = "bankChannelServiceSOAP")
    public BankChannelService getBankChannelServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://172.25.140.21:8070/bankChannelService/", "bankChannelServiceSOAP"), BankChannelService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKCHANNELSERVICE_EXCEPTION!= null) {
            throw BANKCHANNELSERVICE_EXCEPTION;
        }
        return BANKCHANNELSERVICE_WSDL_LOCATION;
    }

}
